[16.0][ADD] product_packaging_multi_barcode
QuocDuong1306/stock-logistics-barcode pull request #1
Opened 2023-08-09 10:11 UTC by QuocDuong1306

2023-08-09 11:37 UTC, nilshamerlinck requested changes

2023-08-09 11:37 UTC, nilshamerlinck commented on product_packaging_multi_barcode/models/product_barcode.py
> +                packaging = barcode.packaging_id
might also need a sudo() here, same reasoning

2023-08-10 01:17 UTC, QuocDuong1306 commented
Hi @nilshamerlinck , i updated

2023-08-10 02:09 UTC, nilshamerlinck approved these changes

2024-03-07 09:09 UTC, merged